### ISSUE TITLE
Windyty API doesn't work?!

### ISSUE THREAD

**Issue by akiohansen** [windycom/API#1]
Hey,

at first, I'm really impressed by your windyty project, which is awesome! Great job and thank you as well for offering the API to others! :)

I'm actually trying to use your offered Windyty API, but at the GitHub webpage it is written:
"Get your API key at this address, and then create html file with following code:" , but where is "this address" ? How do I get an API key?
Furthermore the address api.windyty.com doesn't seem to respond. That's why I want to ask you, if the windyty API is still working and an active project? ;-)

Thanks a lot for all your efforts and best regards,
Akio

**Comment by windyty** [comment]
You are here too early. We still develp this
