### ISSUE TITLE
Default Windy CSS hides scale display

### ISSUE THREAD

**Issue by coremarine** [windycom/API#13]
It seems that Windy API hides .leaflet-control-container so L.control.scale().addTo(map) does not work by default and must be overriden in CSS. It works when adding
```
#windy #map-container .leaflet-control-container {
    display:block !important;
}
```
to the local CSS. I understand that Windy uses custom zoom controls but scale should not be hidden by default.

**Comment by mdorda** [comment]
Thank you for your suggestion and report. We have decided to not change this behaviour.
