### ISSUE TITLE
Thunderstorm layer is in Metric

### ISSUE THREAD

**Issue by StewAlexanderACC** [windycom/API#14]
Under the `Rain, Thunder`, the “Thunderstorm” layer key is in metric 

Yes it’s the SI system, but perhaps a 3rd toggle for American / metric / SI units? So people can choose?

Thanks …

Best Regards,
Stewart Alexander

**Comment by mdorda** [comment]
```js
windyAPI.store.set('metric_rain', 'in');
windyAPI.store.set('metric_rain', 'mm');
```

should do the job.
