### ISSUE TITLE
Please help.

### ISSUE THREAD

**Issue by torobekov** [windycom/API#17]
http://se.kiteforum.com/spots-test
here I put hello world code. But getting errors on console. Please help.

**Comment by mdorda** [comment]
Hi, these errors are not related to the Windy API. All errors come from mootools, as you can see at stacktrace:

```
...
at Object.get (mootools-core-1.4.5-full-compat-yc.js?c=532:88)
...
```

etc...

Probably some incompatibility between libraries.
