### ISSUE TITLE
mywindy.com links don't seem to work in Safari

### ISSUE THREAD

**Issue by DylanMoriarty** [windycom/API#2]
I've already reached out, but again I'd like to give a strong kudos for the great work you folks have done on this tool.

While testing it out, I noticed that in **Safari (Version 11.0.2)** maps made from https://mywindy.com/dmoriarty/tester load the leaflet portion of the map, but don't seem to be able to load the 'windy' layers- i.e:

![screenshot 2018-01-04 at 4 58 46 pm](https://user-images.githubusercontent.com/9341928/34586007-27bd8f18-f170-11e7-8a3d-5fe4621994c0.png)

Looking in the console you end up with a couple of errors for maps, failed resource loading, and 15 promise rejections.

![screenshot 2018-01-04 at 5 02 23 pm](https://user-images.githubusercontent.com/9341928/34586118-aeaa736a-f170-11e7-9144-a2d2d2c0d5a0.png)

Just wanted to flag for ya'll on the off chance you've seen this before or aren't aware of it.

**Comment by jaffadog** [comment]
this one is fixed.

**Comment by chitgoks** [comment]
after 2 yrs, its dead

**Comment by mdorda** [comment]
Yes, as we noticed 1,5 year ago, we discontinued this old API. Visit https://api.windy.com/ for more informations.
