### ISSUE TITLE
Can't Login / Register As A New User

### ISSUE THREAD

**Issue by Davy49** [windycom/API#25]
Hi,
On the windy.com website, I was trying to login a few day's ago & quickly found out that I couldn't because evidently at one time I was in fact able to do so, but either I didn't save my login information or it's been deleted by the site. I tried to register as a new user, but upon entering the email address's that I normally use, I received a prompt that the entered address had already been used. At this point now I don't know what to do, and of course without being able to login, I can't post anything in the windy community either. Does anyone have any suggestion's ?
Thanks,
David

**Comment by mdorda** [comment]
Not exactly the right place where to ask a community related question :-) This link should do the job: https://community.windy.com/reset

Anyway, be sure you are trying to login in with your email, not your username.
