### ISSUE TITLE
Update Wiki based on my forked Wiki example

### ISSUE THREAD

**Issue by johnblakey** [windycom/API#26]
See my proposed wiki changes at my fork of your repo [https://github.com/johnblakey/API/wiki](https://github.com/johnblakey/API/wiki)

Change List
---
- Added link to Getting Started page on Home wiki page [https://github.com/johnblakey/API/wiki](https://github.com/johnblakey/API/wiki)

- Corrected typo on Getting-Started page ('created' to 'create') [https://github.com/johnblakey/API/wiki/Getting-Started](https://github.com/johnblakey/API/wiki/Getting-Started)

- Updated the placeholder footer text with 'For user related questions or discussions see community.windy.com'

- Updated the placeholder sidebar text with links to wiki pages

---

Unfortunately I can't create a pull request for the wiki section of a github repo for an easy comparison and merge.

**Note**: the links need to be modified to not reflect my forked version

**Comment by mdorda** [comment]
Thanks, I found out the whole wiki is obsolete. We changed our API a year ago, so I completely removed the wiki.
