### ISSUE TITLE
Coule you please increase the service in China

### ISSUE THREAD

**Issue by yuanyuan-xy** [windycom/API#27]
Thank you for generously giving us such a beautiful map API for free, but there seems to be no way to open the API website in China. Could you deploy a service in China so that millions of Chinese developers can see such a beautiful map!

**Comment by mdorda** [comment]
Windy.com is blocked in China, there is unfortunately nothing we can do for you.

**Comment by yuanyuan-xy** [comment]
Thank you for ask

> Windy.com is blocked in China, there is unfortunately nothing we can do for you.

I see. Thanks for the answer
