### ISSUE TITLE
Windy + Flutter?

### ISSUE THREAD

**Issue by AAverin** [windycom/API#28]
Did anybody already explore if Windy can be displayed in flutter somehow, maybe using `fleaflet` library?
https://github.com/fleaflet/flutter_map/issues/92

**Comment by mdorda** [comment]
Closed due to inactivity.

**Comment by AAverin** [comment]
@mdorda I would love to see some activity here from Windy developers. It would be great to be able to use Windy in Flutter mobile apps.

**Comment by mdorda** [comment]
Windy API is a leaflet extension. This is way it supposed to be used the API. We are sorry, but there is no plan to change this.

**Comment by AAverin** [comment]
`flutter_map` is leaflet implementation for flutter, it also has some plugin support.
I don't have any experience with leaflet and plugins myself so I can't contribute much, but maybe there could be some communication/collaboration between `windy` and `flutter_map` to find a way to run windy mobile?

**Comment by eclair4151** [comment]
For anyone finding this later, and wants to show a windy view in flutter or iOS/Android, your best bet is just embed everything into a local html/css/js files and load the file locally in an embedded web browser inside your app. 

This means it still feels like a web browser during use, but will load faster, and you can embed the webview in whatever place/size in your app you want. Obvi not as good as a native implementation, but good enough for most use cases.

**Comment by mdorda** [comment]
@eclair4151 Loading files locally is not in accordance with the documentation and terms of use. So in this case, you may find that any update on our side will stop the API from working without any prior warning. I strongly advise against doing this.

**Comment by eclair4151** [comment]
Thank you very much for the heads up. We will move towards loading the content via the web in the embed web view instead for the future.
