### ISSUE TITLE
Lightning tick sounds

### ISSUE THREAD

**Issue by 737simpilot** [windycom/API#33]
First and foremost, I can't even for the life of me figure out how to post to your forum. The screen is whited out like a blizzard and is hard on my eyes as well. I run a phpBB driven forum and the software you're using is a PITA. 

Now to the pertinent.  The issue is the annoying tick sounds for lightning. I loaded the radar map and I heard what I thought was a relay kicking in with my computer or radio gear sitting here. I literally got up and had to check everything. Then I noticed when there was a lightning strike on the map the sound was heard. So, went into the settings to adjust this and nothing was found. If it's there it sure oughta be in the settings and not buried somewhere else. 

I suggest the audio be selectable or changed as this tick sound sounds just like a relay kicking in or something wrong with electronics. 

Thanks.

**Comment by mdorda** [comment]
I am sorry, but the question is not related to the API. There is no radar layer or settings in our API. Closed.
