### ISSUE TITLE
Turkish translate problem

### ISSUE THREAD

**Issue by MuhammedAlmaz** [windycom/API#35]
![Screenshot 2023-05-12 at 11 07 39](https://github.com/windycom/API/assets/17336091/7588761e-df15-4508-b3ed-8ff00bdc771a)
In this screenshot you can see the Dusk label translated to "Şafak" it is wrong. The correct translate should be "Akşam karanlığı". If u translate "Dawn" the result must be "Şafak". Can you change it please?

**Comment by mdorda** [comment]
Thanks, it's been reported to the appropriate team.
