### ISSUE TITLE
Raise windy lib version to leaflet 1.9

### ISSUE THREAD

**Issue by mst94** [windycom/API#38]
Hi,

currently I have to download the windy lib and modify the leaflet version check inside to make it work with the most recent leaflet version.

Because leaflet 1.4 is from 2018 and there have been many improvements since then, I want to ask if it is planned to raise this plugin to be compatible with leaflet 1.9. I think it is just one line of code that has to be changed and that would make our life easier.

Thanks in advance.

**Comment by mdorda** [comment]
In fact, we plan to use leaflet less and less, so the upgrade will almost certainly not happen. We apologize and hope that the API is still usable for you.

**Comment by mst94** [comment]
@mdorda  Thanks for the answer. Do you have alternatives for us to use your API inside a map?
