### ISSUE TITLE
Weather picker fails on mobile

### ISSUE THREAD

**Issue by martijngastkemper** [windycom/API#5]
On mobile the weather picker gives a Javascript error. [windy.com](windy.com) doesn't have this issue.

![screenshot 2018-10-18 at 18 26 02](https://user-images.githubusercontent.com/250662/47169287-6359eb00-d303-11e8-8409-78b3c5e21e54.png)

**Comment by ilblog** [comment]
Not supported on mob devices

**Comment by martijngastkemper** [comment]
How come the weather picker does work on windy.com?
