### ISSUE TITLE
Windy api4 can't be accessed in China

### ISSUE THREAD

**Issue by CHAUMET** [windycom/API#7]
Api4.windy.com cannot be accessed in China 
I tried to use a proxy and still can't access it.
Is there any solution to this problem?

![image](https://user-images.githubusercontent.com/22586470/50747232-d1acaa80-126d-11e9-94bb-58d894eca665.png)

**Comment by mdorda** [comment]
Closed in favor of community forum.

**Comment by yuanyuan-xy** [comment]
你好,请问这个网站你后来打开了吗,我也遇到了这个问题....

**Comment by CHAUMET** [comment]
> 你好,请问这个网站你后来打开了吗,我也遇到了这个问题....

我记得当时电脑死活打不开，但是手机挂vpn可以打开网址。
刚试了下，还是只有手机能打开......

**Comment by yuanyuan-xy** [comment]
> > 你好，请问这个网站你后来打开了吗，我也遇到了这个问题....
> 
> 我记得当时电脑死活打不开，但是手机挂vpn可以打开网址。
> 刚试了下，还是只有手机能打开...

> > 你好，请问这个网站你后来打开了吗，我也遇到了这个问题....
> 
> 我记得当时电脑死活打不开，但是手机挂vpn可以打开网址。
> 刚试了下，还是只有手机能打开...

好吧,感谢老哥~

**Comment by yuanyuan-xy** [comment]
> > 你好,请问这个网站你后来打开了吗,我也遇到了这个问题....
> 
> 我记得当时电脑死活打不开，但是手机挂vpn可以打开网址。
> 刚试了下，还是只有手机能打开.....

> > 你好,请问这个网站你后来打开了吗,我也遇到了这个问题....
> 
> 我记得当时电脑死活打不开，但是手机挂vpn可以打开网址。
> 刚试了下，还是只有手机能打开......

老哥我再问下,这个插件做出来的效果和windy.com一样是吗
